"""
Plain-English explanation generation from classification outputs.
Generates template-grounded explanations without relying on external LLMs.
"""

from __future__ import annotations

from typing import Optional

from defence_recog.inference import PredictionResult


DISCLAIMER_TEXT = (
    "Note: This outcome is a statistical inference generated by an image classifier "
    "operating over a closed 5-class military taxonomy; it is not definitive confirmation."
)


def generate_explanation(result: PredictionResult) -> str:
    """
    Generate a 2 to 4 sentence plain-English summary of the classification result.
    """
    top1_name = result.predicted_display_name
    conf_pct = result.confidence * 100.0

    # Retrieve runner-up info
    runner_up_name: Optional[str] = None
    runner_up_pct: Optional[float] = None
    if len(result.top_k) > 1:
        runner_up = result.top_k[1]
        runner_up_name = runner_up.display_name
        runner_up_pct = runner_up.confidence * 100.0

    sentences = []

    if not result.is_uncertain:
        # Confident prediction
        sentences.append(
            f"The system identified this platform as a **{top1_name}** with a strong confidence score of **{conf_pct:.1f}%**."
        )
        if runner_up_name and runner_up_pct is not None:
            sentences.append(
                f"The closest secondary match was {runner_up_name} at {runner_up_pct:.1f}%, leaving an unambiguous discriminative margin."
            )
        sentences.append(
            "Visual features such as airframe/hull geometry and structural contours strongly align with training profiles."
        )
    else:
        # Uncertain prediction
        sentences.append(
            f"The model's top candidate is **{top1_name}**, but with a tentative confidence of only **{conf_pct:.1f}%**."
        )
        if runner_up_name and runner_up_pct is not None:
            margin_pct = conf_pct - runner_up_pct
            sentences.append(
                f"Prediction ambiguity is high: **{runner_up_name}** is a close runner-up at {runner_up_pct:.1f}% (narrow {margin_pct:.1f}% margin)."
            )
        sentences.append(
            "This low certainty may stem from challenging perspectives, background occlusion, motion blur, or an object outside the 5 defence classes."
        )

    sentences.append(DISCLAIMER_TEXT)
    return " ".join(sentences)
